---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: healthz
  name: healthz
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: healthz
  sessionAffinity: None
  type: ClusterIP
